import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import { join } from "node:path";
import { readFile } from "node:fs/promises";
import { resolveProject } from "../config.js";
import { requireDotaPaths, resolveDotaPaths } from "../dota/paths.js";
import { vmapToText, textToVmap, buildEntityBlock, insertEntity, maxNodeId } from "../dota/vmap.js";
import { categoryForFgdEntity, parseFgdEntities } from "../dota/fgd.js";
import { parseTileGrid, tileToWorld } from "../dota/tilegrid.js";
import { registerMapFile } from "../dota/addoninfo.js";
import { compileProjectMap, projectMapPaths } from "../dota/map-project.js";
import { loadMapContract } from "../dota/map-contract.js";
import { parseManagedTerrain, reconcileMapTerrain } from "../dota/map-terrain.js";
import {
  managedMapPathInputSchema,
  mapSpecificationInputSchema,
  parseMapSpecification,
  reconcileMapSpecification,
  regionDefinitionInputSchema,
  terrainOperationInputSchema,
} from "../dota/map-spec.js";
import { resolveDataPath } from "../util/datapath.js";
import { runMapTransaction } from "../dota/map-transaction.js";
import { renderMapPreview } from "../dota/map-preview.js";
import { MAP_VOLUME_RECIPES } from "../dota/map-volume.js";
import { POINT_BLOCKER_RECIPES } from "../dota/dota-components.js";
import {
  CLIFF_RECIPE_SETS,
  CORE_TERRAIN_RECIPES,
  VALVE_PREFAB_RECIPES,
  validateTerrainRecipeLibrary,
} from "../dota/terrain-recipes.js";
import { writeTextFile, pathExists } from "../util/fsx.js";
import { json, text, image, error, guard, ToolResult } from "../util/result.js";

const NAME_RE = /^[a-z][a-z0-9_]+$/;

const scalar = z.union([z.string(), z.number(), z.boolean()]);
const legacyEntityInputSchema = z.object({
  classname: z.string().min(1),
  origin: z.string().min(1).optional(),
  angles: z.string().min(1).optional(),
  properties: z.record(scalar).optional(),
}).strict();
const legacyPathInputSchema = managedMapPathInputSchema.extend({
  speed: scalar.optional(),
});
type LegacyEntityInput = z.infer<typeof legacyEntityInputSchema>;
type WaypointPathInput = z.infer<typeof legacyPathInputSchema>;

export interface WaypointEntity {
  classname: string;
  origin: string;
  properties: Record<string, string>;
}

export function expandWaypointPath(path: WaypointPathInput): WaypointEntity[] {
  const points = path.points ?? [];
  const startIndex = Number.isInteger(path.startIndex) ? path.startIndex! : 0;
  const classname = path.classname ?? "path_track";
  return points.map((point, offset) => {
    const index = startIndex + offset;
    const properties: Record<string, string> = {
      ...Object.fromEntries(
        Object.entries(path.properties ?? {}).map(([key, value]) => [key, String(value)]),
      ),
      targetname: `${path.name}_${index}`,
    };
    if (offset < points.length - 1) properties.target = `${path.name}_${index + 1}`;
    else if (path.loop && points.length) properties.target = `${path.name}_${startIndex}`;
    if (path.speed !== undefined) properties.speed = String(path.speed);
    return { classname, origin: point.join(" "), properties };
  });
}

function placeEntities(
  textIn: string,
  entities: LegacyEntityInput[],
  paths_: WaypointPathInput[],
  log: string[],
): string {
  let txt = textIn;
  let node = maxNodeId(txt);
  for (const e of entities ?? []) {
    const normalizedProperties = e.properties
      ? Object.fromEntries(Object.entries(e.properties).map(([key, value]) => [key, String(value)]))
      : undefined;
    txt = insertEntity(
      txt,
      buildEntityBlock(
        {
          classname: e.classname,
          origin: e.origin,
          angles: e.angles,
          properties: normalizedProperties,
        },
        ++node,
      ),
    );
    log.push(`entity ${e.classname} @ ${e.origin ?? "0 0 0"}`);
  }
  for (const p of paths_ ?? []) {
    const waypoints = expandWaypointPath(p);
    for (const waypoint of waypoints) {
      txt = insertEntity(txt, buildEntityBlock(waypoint, ++node));
    }
    const startIndex = Number.isInteger(p.startIndex) ? p.startIndex : 0;
    log.push(
      `path "${p.name}": ${waypoints.length} ${p.classname ?? "path_track"} waypoints ` +
        `(first node ${p.name}_${startIndex}${p.loop ? ", looped" : ""})`,
    );
  }
  return txt;
}

const PATHFINDER_TS = `// Compact grid A* — generated by dota2-workshop-mcp (maze TD pathfinding/validation).
export interface PathNode { x: number; y: number; }

export class Grid {
    private blocked: boolean[] = [];
    constructor(public readonly w: number, public readonly h: number) {
        for (let i = 0; i < w * h; i++) this.blocked.push(false);
    }
    inBounds(x: number, y: number): boolean { return x >= 0 && y >= 0 && x < this.w && y < this.h; }
    isBlocked(x: number, y: number): boolean { return !this.inBounds(x, y) || this.blocked[y * this.w + x]; }
    setBlocked(x: number, y: number, b: boolean): void { if (this.inBounds(x, y)) this.blocked[y * this.w + x] = b; }
}

export function findPath(grid: Grid, sx: number, sy: number, ex: number, ey: number): PathNode[] | undefined {
    if (grid.isBlocked(sx, sy) || grid.isBlocked(ex, ey)) return undefined;
    const w = grid.w;
    const BIG = 1e9;
    const open: number[] = [sy * w + sx];
    const came: Record<number, number> = {};
    const gScore: Record<number, number> = {};
    const fScore: Record<number, number> = {};
    gScore[sy * w + sx] = 0;
    fScore[sy * w + sx] = Math.abs(ex - sx) + Math.abs(ey - sy);
    const closed: Record<number, boolean> = {};
    const dirs = [[1, 0], [-1, 0], [0, 1], [0, -1]];
    while (open.length > 0) {
        let bi = 0;
        for (let i = 1; i < open.length; i++) {
            const a = fScore[open[i]]; const b = fScore[open[bi]];
            if ((a === undefined ? BIG : a) < (b === undefined ? BIG : b)) bi = i;
        }
        const cur = open[bi];
        open.splice(bi, 1);
        const cx = cur % w; const cy = Math.floor(cur / w);
        if (cx === ex && cy === ey) {
            const path: PathNode[] = [];
            let c: number | undefined = cur;
            while (c !== undefined) { path.unshift({ x: c % w, y: Math.floor(c / w) }); c = came[c]; }
            return path;
        }
        closed[cur] = true;
        for (const d of dirs) {
            const nx = cx + d[0]; const ny = cy + d[1];
            if (grid.isBlocked(nx, ny)) continue;
            const ni = ny * w + nx;
            if (closed[ni]) continue;
            const cg = gScore[cur]; const tentative = (cg === undefined ? BIG : cg) + 1;
            const ng = gScore[ni];
            if (tentative < (ng === undefined ? BIG : ng)) {
                came[ni] = cur;
                gScore[ni] = tentative;
                fScore[ni] = tentative + Math.abs(ex - nx) + Math.abs(ey - ny);
                if (open.indexOf(ni) < 0) open.push(ni);
            }
        }
    }
    return undefined;
}
`;

async function emitMazeTd(
  tsDir: string,
  o: { waves?: any[]; lives?: number; gridMin?: number[]; gridMax?: number[]; cell?: number; spawn?: number[]; finish?: number[]; overwrite?: boolean },
): Promise<ToolResult> {
  const minx = o.gridMin?.[0] ?? -5120, miny = o.gridMin?.[1] ?? -5120;
  const maxx = o.gridMax?.[0] ?? 5120, maxy = o.gridMax?.[1] ?? 5120;
  const cell = o.cell ?? 256;
  const GW = Math.max(2, Math.round((maxx - minx) / cell));
  const GH = Math.max(2, Math.round((maxy - miny) / cell));
  const toCell = (wx: number, wy: number): [number, number] => [
    Math.max(0, Math.min(GW - 1, Math.floor((wx - minx) / cell))),
    Math.max(0, Math.min(GH - 1, Math.floor((wy - miny) / cell))),
  ];
  const sp = o.spawn ? toCell(o.spawn[0], o.spawn[1]) : [0, Math.floor(GH / 2)];
  const fi = o.finish ? toCell(o.finish[0], o.finish[1]) : [GW - 1, Math.floor(GH / 2)];
  const z = 128;
  const waveList = (o.waves && o.waves.length ? o.waves : [
    { creep: "npc_dota_creep_badguys_melee", count: 18, perSpawn: 3 },
    { creep: "npc_dota_creep_badguys_ranged", count: 21, perSpawn: 3 },
    { creep: "npc_dota_creep_badguys_melee", count: 1, perSpawn: 1, boss: true },
  ]).map((w: any) => `    { creep: "${w.creep}", count: ${w.count ?? 12}, perSpawn: ${w.perSpawn ?? 3}, boss: ${!!w.boss} }`).join(",\n");

  const mazeTs = `// Maze tower-defense director — generated by dota2-workshop-mcp.
// GemTD-style: a walkable grid + A* validation (a build is refused if it would wall
// off the path) + creeps follow the computed path via MoveToPosition. Call
// startTowerDefense() once in-game; call canBuildAt(pos) from your build ability.
import { Grid, findPath, PathNode } from "./pathfinder";

const ORIGIN_X = ${minx};
const ORIGIN_Y = ${miny};
const CELL = ${cell};
const GW = ${GW};
const GH = ${GH};
const GROUND_Z = ${z};
const SPAWN: PathNode = { x: ${sp[0]}, y: ${sp[1]} };
const FINISH: PathNode = { x: ${fi[0]}, y: ${fi[1]} };

interface TdWave { creep: string; count: number; perSpawn: number; boss: boolean; }
const WAVES: TdWave[] = [
${waveList}
];
let g_lives = ${o.lives ?? 50};

const grid = new Grid(GW, GH);

function cellCenter(cx: number, cy: number): Vector {
    return Vector(ORIGIN_X + (cx + 0.5) * CELL, ORIGIN_Y + (cy + 0.5) * CELL, GROUND_Z);
}
function worldToCell(v: Vector): PathNode {
    return { x: Math.floor((v.x - ORIGIN_X) / CELL), y: Math.floor((v.y - ORIGIN_Y) / CELL) };
}

/** Call from your build ability. Returns false (and leaves the cell open) if building
 *  here would block every path from spawn to finish; otherwise marks it blocked. */
export function canBuildAt(this: void, worldPos: Vector): boolean {
    const c = worldToCell(worldPos);
    if (grid.isBlocked(c.x, c.y)) return false;
    grid.setBlocked(c.x, c.y, true);
    const path = findPath(grid, SPAWN.x, SPAWN.y, FINISH.x, FINISH.y);
    if (path === undefined) { grid.setBlocked(c.x, c.y, false); return false; }
    return true;
}

function pathWorld(): Vector[] {
    const p = findPath(grid, SPAWN.x, SPAWN.y, FINISH.x, FINISH.y);
    const out: Vector[] = [];
    if (p === undefined) { out.push(cellCenter(FINISH.x, FINISH.y)); return out; }
    for (const n of p) out.push(cellCenter(n.x, n.y));
    return out;
}

export function startTowerDefense(this: void): void {
    print("[TD maze] grid " + GW + "x" + GH + ", " + WAVES.length + " waves");
    spawnWave(0);
}
function spawnWave(this: void, index: number): void {
    const wave = WAVES[index];
    if (!wave) { print("[TD maze] cleared!"); return; }
    let spawned = 0;
    Timers.CreateTimer(0, () => {
        for (let k = 0; k < wave.perSpawn && spawned < wave.count; k++) { spawnCreep(wave); spawned++; }
        if (spawned < wave.count) return 0.6;
        Timers.CreateTimer(12, () => { spawnWave(index + 1); return undefined; });
        return undefined;
    });
}
function spawnCreep(this: void, wave: TdWave): void {
    const unit = CreateUnitByName(wave.creep, cellCenter(SPAWN.x, SPAWN.y), true, undefined, undefined, DotaTeam.BADGUYS);
    unit.SetControllableByPlayer(-1, false);
    if (wave.boss) unit.SetModelScale(1.6);
    (unit as any).path = pathWorld();
    (unit as any).ti = 0;
    follow(unit);
}
function follow(this: void, unit: CDOTA_BaseNPC): void {
    unit.SetContextThink("td_maze_follow", () => {
        if (!IsValidEntity(unit) || !unit.IsAlive()) return undefined;
        const path = (unit as any).path as Vector[];
        let ti = (unit as any).ti as number;
        if (ti >= path.length) { leak(unit); return undefined; }
        if (((unit.GetAbsOrigin() - path[ti]) as Vector).Length2D() < 120) {
            ti = ti + 1; (unit as any).ti = ti;
            if (ti < path.length) unit.MoveToPosition(path[ti]);
            return 0.2;
        }
        unit.MoveToPosition(path[ti]);
        return 0.3;
    }, 0);
}
function leak(this: void, unit: CDOTA_BaseNPC): void {
    g_lives -= 1;
    print("[TD maze] leak! lives = " + g_lives);
    if (IsValidEntity(unit)) unit.RemoveSelf();
}
`;

  const pfFile = join(tsDir, "td", "pathfinder.ts");
  const mzFile = join(tsDir, "td", "td_maze.ts");
  if (!o.overwrite && ((await pathExists(pfFile)) || (await pathExists(mzFile)))) {
    return error(`Maze TD files exist (${pfFile}). Pass overwrite=true.`);
  }
  await writeTextFile(pfFile, PATHFINDER_TS, { encoding: "utf8" });
  await writeTextFile(mzFile, mazeTs, { encoding: "utf8" });
  return json(
    { pathfinder: pfFile, director: mzFile, grid: [GW, GH], spawn: sp, finish: fi },
    `Maze TD scaffolded:\n  + ${pfFile}\n  + ${mzFile}\nGrid ${GW}x${GH} (cell ${cell}), spawn cell ${sp.join(",")}, finish ${fi.join(",")}.\n` +
      `Call startTowerDefense() from GameMode; gate your build ability with canBuildAt(pos). Needs the template's Timers lib. npm run build, then launch.`,
  );
}

export function registerMapGenTools(server: McpServer) {
  server.registerTool(
    "map_recipe_catalog",
    {
      title: "Known-good Dota map recipes",
      description:
        "List the MCP's validated Valve-derived terrain core, cliff decoration, ramp-safe fallback, and official " +
        "prefab references plus checked solid-volume recipes. Optionally verify that referenced Valve prefabs are " +
        "present in the installed Workshop content.",
      inputSchema: {
        category: z
          .enum(["base", "ancient", "tower", "fountain", "shop", "camp", "boss", "volume"])
          .optional(),
        verifyInstalled: z.boolean().optional().describe("Check prefab paths under the installed Dota content tree."),
      },
    },
    guard(async ({ category, verifyInstalled }): Promise<ToolResult> => {
      const errors = validateTerrainRecipeLibrary();
      const dota = verifyInstalled ? await resolveDotaPaths() : undefined;
      const prefabs = await Promise.all(
        VALVE_PREFAB_RECIPES
          .filter((recipe) => !category || (category !== "volume" && recipe.category === category))
          .map(async (recipe) => ({
            ...recipe,
            installed:
              !verifyInstalled || !dota
                ? null
                : await pathExists(join(dota.root, "content", "dota", recipe.source)),
          })),
      );
      return json(
        {
          valid: errors.length === 0,
          validationErrors: errors,
          coreTerrain: CORE_TERRAIN_RECIPES,
          cliffSets: CLIFF_RECIPE_SETS,
          rampFallback: "Ramp cells use the matching core corner tile without decorative cliff layers.",
          volumeRecipes: !category || category === "volume" ? MAP_VOLUME_RECIPES : {},
          pointBlockerRecipes: !category || category === "base" ? POINT_BLOCKER_RECIPES : {},
          prefabs,
          installVerified: verifyInstalled === true && Boolean(dota),
        },
        `Recipe library ${errors.length ? `has ${errors.length} validation error(s)` : "is valid"}: ` +
          `${CORE_TERRAIN_RECIPES.length} terrain cores, ${CLIFF_RECIPE_SETS.length} cliff sets, ` +
          `${prefabs.length} Valve prefab references, ` +
          `${!category || category === "volume" ? Object.keys(MAP_VOLUME_RECIPES).length : 0} checked volume recipes.`,
      );
    }),
  );

  server.registerTool(
    "entity_catalog",
    {
      title: "Dota map entity catalog",
      description:
        "List placeable Dota map entities (classname + purpose + key keyvalues). Text searches also consult the " +
        "installed official dota.fgd, so engine entities missing from the curated catalog can still be discovered. " +
        "Filter by query or category (spawn, marker, path, trigger, logic, light, env, prop, dota, fx, vision, world).",
      inputSchema: {
        query: z.string().optional(),
        category: z.string().optional(),
        includeOfficial: z
          .boolean()
          .optional()
          .describe("Include all installed dota.fgd classes even without a text query (default false)."),
        limit: z.number().int().positive().max(500).optional(),
      },
    },
    guard(async ({ query, category, includeOfficial, limit }): Promise<ToolResult> => {
      const data = JSON.parse(await readFile(await resolveDataPath("entity-catalog.json"), "utf8"));
      type CatalogEntry = {
        name: string;
        category: string;
        purpose: string;
        keyValues?: string;
        source?: "curated" | "official-fgd";
        classType?: string;
        bases?: string[];
      };
      let list: CatalogEntry[] = (data.entities as CatalogEntry[]).map((entry) => ({
        ...entry,
        source: "curated",
      }));
      if (query || includeOfficial) {
        const dota = await resolveDotaPaths();
        const fgdPath = dota ? join(dota.dotaGameDir, "dota.fgd") : undefined;
        if (fgdPath && (await pathExists(fgdPath))) {
          const known = new Set(list.map((entry) => entry.name));
          const official = parseFgdEntities(await readFile(fgdPath, "utf8"))
            .filter((entry) => !known.has(entry.name))
            .map<CatalogEntry>((entry) => ({
              name: entry.name,
              category: categoryForFgdEntity(entry.name),
              purpose: entry.description || `Official ${entry.classType} from dota.fgd.`,
              keyValues: entry.properties
                .map((property) => `${property.kind === "keyvalue" ? "" : `${property.kind} `}${property.name}`)
                .join(", "),
              source: "official-fgd",
              classType: entry.classType,
              bases: entry.bases,
            }));
          list.push(...official);
        }
      }
      if (category) list = list.filter((e) => e.category.toLowerCase() === category.toLowerCase());
      if (query) {
        const q = query.toLowerCase();
        list = list.filter((e) => e.name.toLowerCase().includes(q) || e.purpose.toLowerCase().includes(q) || (e.keyValues ?? "").toLowerCase().includes(q));
      }
      list = list.slice(0, limit ?? 100);
      return json(
        { count: list.length, entities: list },
        list
          .map(
            (e) =>
              `[${e.category}] ${e.name}${e.source === "official-fgd" ? " (official FGD)" : ""}\n` +
              `    ${e.purpose}\n    keys: ${e.keyValues || "(position only)"}`,
          )
          .join("\n") || "No entities match.",
      );
    }),
  );

  server.registerTool(
    "map_terrain",
    {
      title: "Shape map terrain",
      description:
        "Apply the same validated terrain operations used by map specifications and map_sync_contract. Coordinates " +
        "are in tile units. Supports fill, height, water, tileset, and ramp operations over rect, circle, ring, path, " +
        "polygon, named region, or managedPath shapes. Pass reusable region definitions alongside the operations; " +
        "managedPath shapes resolve against the project's map contract. Valid cliff orientation and tile recipes are " +
        "regenerated automatically. Recompile after (or pass recompile=true).",
      inputSchema: {
        projectRoot: z.string().optional(),
        map: z.string(),
        ops: z.array(terrainOperationInputSchema).min(1).describe("Validated terrain operations."),
        regions: z
          .record(regionDefinitionInputSchema)
          .optional()
          .describe("Optional reusable named terrain shapes referenced by region operations."),
        contractFile: z
          .string()
          .optional()
          .describe("Contract used to resolve managedPath shapes. Defaults to .dota-workshop/map-contract.json."),
        apply: z.boolean().optional().describe("Write the planned terrain changes (default false)."),
        recompile: z.boolean().optional().describe("Compile after applying; requires apply=true."),
      },
    },
    guard(async ({ projectRoot, map, ops, regions, contractFile, apply, recompile }): Promise<ToolResult> => {
      const dota = await requireDotaPaths();
      const project = await resolveProject(projectRoot);
      const p = projectMapPaths(dota, project, map);
      if (!(await pathExists(p.contentVmap))) return error(`Map not found: ${p.contentVmap}. Create it with map_create or map_build.`);
      if (recompile && !apply) return error("recompile=true requires apply=true; preview mode never compiles or writes files.");
      const log: string[] = [];
      const needsManagedPaths = ops.some(
        (operation) => operation.op !== "fill" && operation.shape.kind === "managedPath",
      );
      const contract = needsManagedPaths
        ? await loadMapContract(project.root, map, contractFile, parseMapSpecification)
        : undefined;
      if (needsManagedPaths && !contract) {
        return error(`Terrain operations reference managedPath shapes, but no map contract was found under ${project.root}.`);
      }
      const operations = parseMapSpecification(
        {
          regions,
          managedPaths: contract?.contract.managedPaths ?? [],
          managedTerrain: ops,
        },
        `map_terrain(${map})`,
      ).managedTerrain ?? [];
      const current = await vmapToText(dota.dmxconvertExe, p.contentVmap);
      const result = reconcileMapTerrain(current, operations, contract?.contract.managedPaths ?? []);
      const transaction = apply && (result.changed || recompile)
        ? await runMapTransaction({
            projectRoot: project.root,
            label: `${map}-terrain`,
            trackedPaths: [p.contentVmap, ...(recompile ? [p.gameVpk] : [])],
            action: async () => {
              if (result.changed) await textToVmap(dota.dmxconvertExe, result.text, p.contentVmap);
              if (recompile) {
                const res = await compileProjectMap(dota, project, map);
                const compiled = res.code === 0 && (await pathExists(p.installedGameVpk));
                if (!compiled) {
                  throw new Error(
                    `Compilation failed (exit ${res.code ?? "unknown"}).\n${(res.stderr || res.stdout).slice(-1600)}`,
                  );
                }
              }
              return { recompiled: recompile === true };
            },
          })
        : undefined;
      if (transaction && !transaction.committed) {
        const failure = json(
          {
            map,
            applied: false,
            rolledBack: transaction.rolledBack,
            backupDirectory: transaction.backupDirectory,
            error: transaction.error,
            rollbackErrors: transaction.rollbackErrors,
          },
          `Terrain update failed and ${transaction.rolledBack ? "was rolled back safely" : "the rollback needs attention"}.\n` +
            `Backup: ${transaction.backupDirectory}\n${transaction.error ?? "Unknown transaction failure."}`,
        );
        failure.isError = true;
        return failure;
      }
      log.push(
        `terrain ${apply ? (result.changed ? "updated" : "unchanged") : "preview"}: ` +
          `${result.changedHeightVertices} height, ${result.changedWaterVertices} water, ` +
          `${result.changedTilesetCells} tileset, ${result.changedOrientationCells} orientation, ` +
          `${result.changedConfigurationCells} recipe, ${result.changedPathEdges} path-edge cells`,
      );
      if (!apply && result.changed) log.push("No files changed. Pass apply=true to write this plan.");
      if (apply && recompile) log.push(`recompiled -> ${p.gameVpk}`);
      if (transaction) log.push(`recovery backup -> ${transaction.backupDirectory}`);
      return json(
        {
          map,
          changed: result.changed,
          applied: apply === true,
          recompiled: apply === true && recompile === true,
          backupDirectory: transaction?.backupDirectory,
          rolledBack: false,
          operations: result.operations,
          changedHeightVertices: result.changedHeightVertices,
          changedWaterVertices: result.changedWaterVertices,
          changedTilesetCells: result.changedTilesetCells,
          changedOrientationCells: result.changedOrientationCells,
          changedConfigurationCells: result.changedConfigurationCells,
          changedPathEdges: result.changedPathEdges,
        },
        log.join("\n"),
      );
    }),
  );

  server.registerTool(
    "map_build",
    {
      title: "Build a map from a validated specification",
      description:
        "Generate a whole playable map in one call. Prefer specification, which uses the same validated desired-state " +
        "format as map_sync_contract: managedTerrain, managedEntities, managedAbsentEntities, managedPaths, checked " +
        "managedVolumes, and " +
        "requiredEntities, plus reusable regions, components, and transformed placements. Legacy terrain/entities/paths " +
        "remain supported. Terrain coordinates are tile units; entity/path coordinates are world units.",
      inputSchema: {
        projectRoot: z.string().optional(),
        name: z.string(),
        maxPlayers: z.number().int().min(1).max(24).optional(),
        specification: mapSpecificationInputSchema
          .optional()
          .describe("Preferred desired-state map specification; uses the map contract format."),
        terrain: z.array(terrainOperationInputSchema).optional().describe("Legacy terrain operations (tile coords)."),
        entities: z.array(legacyEntityInputSchema).optional().describe("Legacy entity list (world coords)."),
        paths: z.array(legacyPathInputSchema).optional().describe(
          "[{name, points:[[x,y,z]...], classname?, startIndex?, loop?, speed?, properties?}] -> chained waypoints. " +
            "Defaults to path_track starting at _0; Dota creep routes usually use classname:'path_corner', startIndex:1.",
        ),
        compile: z.boolean().optional(),
        overwrite: z.boolean().optional(),
        dryRun: z.boolean().optional().describe("Report the generated changes without writing, registering, or compiling."),
      },
    },
    guard(async ({ projectRoot, name, maxPlayers, specification, terrain, entities, paths: paths_, compile, overwrite, dryRun }): Promise<ToolResult> => {
      if (!NAME_RE.test(name)) return error(`Invalid map name "${name}".`);
      if (specification && ((terrain?.length ?? 0) || (entities?.length ?? 0) || (paths_?.length ?? 0))) {
        return error("Use specification or legacy terrain/entities/paths, not both.");
      }
      const parsedSpecification = specification
        ? parseMapSpecification(specification, `map_build specification for "${name}"`)
        : undefined;
      if (parsedSpecification?.map && parsedSpecification.map !== name) {
        return error(`Map specification is for "${parsedSpecification.map}", not "${name}".`);
      }
      const dota = await requireDotaPaths();
      const project = await resolveProject(projectRoot);
      const p = projectMapPaths(dota, project, name);
      if (!(await pathExists(p.baseTemplate))) return error(`Template base map not found: ${p.baseTemplate}`);
      const mapExists = await pathExists(p.contentVmap);
      if (mapExists && !overwrite && !dryRun) return error(`Map "${name}" exists (pass overwrite=true).`);

      const log: string[] = [`prepared "${name}" from the template`];
      let txt = await vmapToText(dota.dmxconvertExe, p.baseTemplate);
      let specificationChangeReport: unknown;
      if (parsedSpecification) {
        const result = reconcileMapSpecification(txt, parsedSpecification);
        if (result.entities.conflicts.length) {
          return error(`Map specification has ambiguous duplicate targetnames: ${result.entities.conflicts.join(", ")}`);
        }
        txt = result.text;
        specificationChangeReport = {
          entities: {
            added: result.entities.added,
            updated: result.entities.updated,
            removed: result.entities.removed,
            unchanged: result.entities.unchanged,
          },
          volumes: {
            added: result.volumes.added,
            updated: result.volumes.updated,
            unchanged: result.volumes.unchanged,
          },
          terrain: {
            changed: result.terrain.changed,
            changedHeightVertices: result.terrain.changedHeightVertices,
            changedWaterVertices: result.terrain.changedWaterVertices,
            changedTilesetCells: result.terrain.changedTilesetCells,
            changedOrientationCells: result.terrain.changedOrientationCells,
            changedConfigurationCells: result.terrain.changedConfigurationCells,
            changedPathEdges: result.terrain.changedPathEdges,
          },
        };
        log.push(
          `specification: add ${result.entities.added.length}, update ${result.entities.updated.length}, ` +
            `remove ${result.entities.removed.length}; volumes add ${result.volumes.added.length}, ` +
            `update ${result.volumes.updated.length}; terrain ${result.terrain.changed ? "changed" : "unchanged"}`,
        );
      } else {
        if (terrain?.length) {
          const operations = parseManagedTerrain(terrain, "terrain", `map_build(${name})`) ?? [];
          const pathReferences = (paths_ ?? []).map((managedPath) => ({
            name: managedPath.name,
            points: managedPath.points,
          }));
          const result = reconcileMapTerrain(txt, operations, pathReferences);
          txt = result.text;
          log.push(
            `terrain: ${operations.length} operations; ${result.changedHeightVertices} height, ` +
              `${result.changedConfigurationCells} recipe, ${result.changedPathEdges} path-edge changes`,
          );
        }
        if (entities?.length || paths_?.length) {
          txt = placeEntities(txt, entities ?? [], paths_ ?? [], log);
        }
      }
      if (dryRun) {
        log.push(
          `Dry run only: would ${mapExists ? "replace" : "create"} ${p.contentVmap}, register it in addoninfo, ` +
            `and ${compile ? "compile it" : "leave compilation for later"}.`,
        );
        return json(
          {
            name,
            dryRun: true,
            wouldOverwrite: mapExists,
            wouldCompile: compile === true,
            vmap: p.contentVmap,
            changes: specificationChangeReport,
          },
          log.join("\n"),
        );
      }

      const transaction = await runMapTransaction({
        projectRoot: project.root,
        label: `${name}-build`,
        trackedPaths: [p.contentVmap, p.addoninfo, ...(compile ? [p.gameVpk] : [])],
        action: async () => {
          await textToVmap(dota.dmxconvertExe, txt, p.contentVmap);
          await registerMapFile(p.addoninfo, name, maxPlayers ?? 10);
          if (compile) {
            const res = await compileProjectMap(dota, project, name);
            const compiled = res.code === 0 && (await pathExists(p.installedGameVpk));
            if (!compiled) {
              throw new Error(
                `Compilation failed (exit ${res.code ?? "unknown"}).\n${(res.stderr || res.stdout).slice(-1600)}`,
              );
            }
          }
          return { compiled: compile === true };
        },
      });
      if (!transaction.committed) {
        const failure = json(
          {
            name,
            applied: false,
            rolledBack: transaction.rolledBack,
            backupDirectory: transaction.backupDirectory,
            error: transaction.error,
            rollbackErrors: transaction.rollbackErrors,
          },
          `Map build failed and ${transaction.rolledBack ? "was rolled back safely" : "the rollback needs attention"}.\n` +
            `Backup: ${transaction.backupDirectory}\n${transaction.error ?? "Unknown transaction failure."}`,
        );
        failure.isError = true;
        return failure;
      }

      log.push(`${mapExists ? "replaced" : "created"} + registered "${name}"`);
      if (compile) {
        log.push(`compiled -> ${p.installedGameVpk}`);
      } else {
        log.push(`Next: map_compile name="${name}", then addon_launch_custom_game map="${name}".`);
      }
      log.push(`recovery backup -> ${transaction.backupDirectory}`);
      return json(
        {
          name,
          dryRun: false,
          applied: true,
          compiled: compile === true,
          vmap: p.contentVmap,
          backupDirectory: transaction.backupDirectory,
          rolledBack: false,
        },
        log.join("\n"),
      );
    }),
  );

  server.registerTool(
    "map_preview",
    {
      title: "Preview a map (top-down image)",
      description:
        "Render a diagnostic top-down image without launching Dota: terrain contours, cliffs, ramps, water, currents, " +
        "entities, waypoint paths, tower ranges, camps, objectives, minimap bounds, checked trigger/blocker volumes, " +
        "terrain holes, and unreachable regions.",
      inputSchema: {
        projectRoot: z.string().optional(),
        map: z.string(),
        scale: z.number().int().min(2).max(16).optional(),
        showContours: z.boolean().optional(),
        showCliffs: z.boolean().optional(),
        showRamps: z.boolean().optional(),
        showEntities: z.boolean().optional(),
        showPaths: z.boolean().optional(),
        showTowerRanges: z.boolean().optional(),
        showCamps: z.boolean().optional(),
        showObjectives: z.boolean().optional(),
        showCurrents: z.boolean().optional(),
        showMinimapBounds: z.boolean().optional(),
        showReachability: z.boolean().optional(),
        showVolumes: z.boolean().optional(),
        showVisionBlockers: z.boolean().optional(),
      },
    },
    guard(async ({
      projectRoot,
      map,
      scale,
      showContours,
      showCliffs,
      showRamps,
      showEntities,
      showPaths,
      showTowerRanges,
      showCamps,
      showObjectives,
      showCurrents,
      showMinimapBounds,
      showReachability,
      showVolumes,
      showVisionBlockers,
    }): Promise<ToolResult> => {
      const dota = await requireDotaPaths();
      const project = await resolveProject(projectRoot);
      const p = projectMapPaths(dota, project, map);
      if (!(await pathExists(p.contentVmap))) return error(`Map not found: ${p.contentVmap}.`);
      const rendered = renderMapPreview(await vmapToText(dota.dmxconvertExe, p.contentVmap), {
        scale,
        showContours,
        showCliffs,
        showRamps,
        showEntities,
        showPaths,
        showTowerRanges,
        showCamps,
        showObjectives,
        showCurrents,
        showMinimapBounds,
        showReachability,
        showVolumes,
        showVisionBlockers,
      });
      const reachability = {
        walkableCellCount: rendered.reachability.walkableCellCount,
        reachableCellCount: rendered.reachability.reachableCellCount,
        unreachableCellCount: rendered.reachability.unreachableCellCount,
        holeCellCount: rendered.reachability.holeCellCount,
        volumeBlockedCellCount: rendered.reachability.volumeBlockedCellCount,
        regions: rendered.reachability.regions,
        findings: rendered.reachability.findings,
      };
      const caption =
        `Diagnostic preview of "${map}" (${rendered.stats.width}x${rendered.stats.height}). ` +
        `${rendered.stats.cliffCells} cliff, ${rendered.stats.rampCells} ramp, ` +
        `${rendered.stats.unreachableCells} unreachable, ${rendered.stats.holeCells} hole cells. ` +
        `Legend: ${Object.entries(rendered.stats.legend).map(([name, value]) => `${name}=${value}`).join("; ")}.`;
      return {
        content: [
          { type: "text", text: caption },
          { type: "image", data: rendered.png.toString("base64"), mimeType: "image/png" },
        ],
        structuredContent: { map, stats: rendered.stats, reachability },
      };
    }),
  );

  server.registerTool(
    "scaffold_td",
    {
      title: "Scaffold a tower-defense director",
      description:
        "Generate a TypeScript tower-defense director vscript (waypoint table + declarative wave/boss table + wave " +
        "spawner + per-creep waypoint follower via ExecuteOrderFromTable + leak/lives) — the canonical Dota TD pattern. " +
        "Pair the waypoints with a map_build path. Call startTowerDefense() from your GameMode after the game starts.",
      inputSchema: {
        projectRoot: z.string().optional(),
        waypoints: z.array(z.array(z.number())).optional().describe("Ordered creep path in WORLD coords [[x,y,z],...] (match a map_build path). Required unless maze=true."),
        waves: z.array(z.any()).optional().describe("[{creep, count, perSpawn?, boss?}] — default sample waves if omitted."),
        lives: z.number().int().optional(),
        maze: z.boolean().optional().describe("Maze TD: also emit a grid A* pathfinder + build validation (can't fully block the path), creeps follow the computed path (GemTD-style)."),
        gridMin: z.array(z.number()).optional().describe("Maze grid world min [x,y] (default [-5120,-5120])."),
        gridMax: z.array(z.number()).optional().describe("Maze grid world max [x,y] (default [5120,5120])."),
        cell: z.number().optional().describe("Maze cell size in world units (default 256)."),
        spawn: z.array(z.number()).optional().describe("Maze spawn world [x,y] (default near gridMin)."),
        finish: z.array(z.number()).optional().describe("Maze finish world [x,y] (default near gridMax)."),
        overwrite: z.boolean().optional(),
      },
    },
    guard(async (args): Promise<ToolResult> => {
      const { projectRoot, waypoints, waves, lives, maze, gridMin, gridMax, cell, spawn, finish, overwrite } = args as any;
      const project = await resolveProject(projectRoot);
      if (!project.tsVscriptsDir) return error("This project has no src/vscripts (not a TS template).");
      if (maze) {
        const r = await emitMazeTd(project.tsVscriptsDir, { waves, lives, gridMin, gridMax, cell, spawn, finish, overwrite });
        return r;
      }
      if (!waypoints || !waypoints.length) return error("waypoints are required (or pass maze=true for a maze TD).");
      const wps = ((waypoints || []) as number[][]).map((p) => `Vector(${p[0]}, ${p[1]}, ${p[2] ?? 128})`).join(",\n    ");
      const waveList = (waves && waves.length ? waves : [
        { creep: "npc_dota_creep_badguys_melee", count: 18, perSpawn: 3 },
        { creep: "npc_dota_creep_badguys_ranged", count: 21, perSpawn: 3 },
        { creep: "npc_dota_creep_badguys_melee", count: 1, perSpawn: 1, boss: true },
      ]).map((w: any) => `  { creep: "${w.creep}", count: ${w.count ?? 12}, perSpawn: ${w.perSpawn ?? 3}, boss: ${!!w.boss} }`).join(",\n");
      const ts = `// Tower-defense director — generated by dota2-workshop-mcp.
// Canonical pattern learned from shipping TD games: a waypoint table + declarative
// wave table + a spawner + a per-creep waypoint follower (ExecuteOrderFromTable
// MOVE_TO_POSITION, advancing on proximity) + leak/lives. Call startTowerDefense()
// from your GameMode once the game is in progress.

interface TdWave { creep: string; count: number; perSpawn: number; boss: boolean; }

const WAYPOINTS: Vector[] = [
    ${wps}
];

const WAVES: TdWave[] = [
${waveList}
];

let g_lives = ${lives ?? 50};
const ARRIVE_RADIUS = 150;
const SPAWN_INTERVAL = 0.6;
const WAVE_GAP = 12;

export function startTowerDefense(this: void): void {
    print("[TD] starting, " + WAVES.length + " waves, " + WAYPOINTS.length + " waypoints");
    spawnWave(0);
}

function spawnWave(this: void, index: number): void {
    const wave = WAVES[index];
    if (!wave) { print("[TD] all waves cleared!"); return; }
    let spawned = 0;
    Timers.CreateTimer(0, () => {
        for (let k = 0; k < wave.perSpawn && spawned < wave.count; k++) { spawnCreep(wave); spawned++; }
        if (spawned < wave.count) return SPAWN_INTERVAL;
        Timers.CreateTimer(WAVE_GAP, () => { spawnWave(index + 1); return undefined; });
        return undefined;
    });
}

function spawnCreep(this: void, wave: TdWave): void {
    const unit = CreateUnitByName(wave.creep, WAYPOINTS[0], true, undefined, undefined, DotaTeam.BADGUYS);
    unit.SetControllableByPlayer(-1, false);
    if (wave.boss) unit.SetModelScale(1.6);
    (unit as any).tdIndex = 1;
    advance(unit);
}

function advance(this: void, unit: CDOTA_BaseNPC): void {
    const i = (unit as any).tdIndex as number;
    if (i >= WAYPOINTS.length) { leak(unit); return; }
    ExecuteOrderFromTable({ UnitIndex: unit.entindex(), OrderType: UnitOrder.MOVE_TO_POSITION, Position: WAYPOINTS[i] });
    unit.SetContextThink("td_follow", () => {
        if (!IsValidEntity(unit) || !unit.IsAlive()) return undefined;
        if (((unit.GetAbsOrigin() - WAYPOINTS[i]) as Vector).Length2D() < ARRIVE_RADIUS) {
            (unit as any).tdIndex = i + 1;
            advance(unit);
            return undefined;
        }
        return 0.25;
    }, 0.25);
}

function leak(this: void, unit: CDOTA_BaseNPC): void {
    g_lives -= 1;
    print("[TD] leak! lives = " + g_lives);
    if (IsValidEntity(unit)) unit.RemoveSelf();
    if (g_lives <= 0) print("[TD] game over");
}
`;
      const file = join(project.tsVscriptsDir, "td", "td_director.ts");
      if ((await pathExists(file)) && !overwrite) return error(`${file} exists (pass overwrite=true).`);
      await writeTextFile(file, ts, { encoding: "utf8" });
      return json(
        { file, waypoints: (waypoints || []).length, waves: (waves && waves.length) || 3 },
        `Wrote ${file}\nCall it from GameMode: import { startTowerDefense } from "./td/td_director"; then startTowerDefense() once PRE_GAME/IN_PROGRESS. Requires the template's Timers lib. Run npm run build, then launch.`,
      );
    }),
  );

  server.registerTool(
    "map_tile_to_world",
    {
      title: "Tile→world coordinate helper",
      description: "Convert tile-grid coordinates to world units for a map (so terrain and entity positions line up).",
      inputSchema: { projectRoot: z.string().optional(), map: z.string(), tx: z.number(), ty: z.number() },
    },
    guard(async ({ projectRoot, map, tx, ty }): Promise<ToolResult> => {
      const dota = await requireDotaPaths();
      const project = await resolveProject(projectRoot);
      const p = projectMapPaths(dota, project, map);
      if (!(await pathExists(p.contentVmap))) return error(`Map not found: ${p.contentVmap}.`);
      const g = parseTileGrid(await vmapToText(dota.dmxconvertExe, p.contentVmap));
      const [wx, wy] = tileToWorld(g, tx, ty);
      return json({ map, tile: [tx, ty], world: [wx, wy], grid: [g.width, g.height], tileSize: g.tileSize, origin: g.origin }, `tile (${tx},${ty}) -> world (${wx}, ${wy})  [grid ${g.width}x${g.height}, ${g.tileSize}u/tile]`);
    }),
  );
}
